### ISSUE TITLE
kaesar-pbkdf2 should be available via MELPA

### ISSUE THREAD

**Issue by thomp** [mhayashi1120/Emacs-kaesar#1]
;; Package-Requires: ((emacs "24.3") (kaesar-pbkdf2 "0.9.0")) 

results in MELPA (https://melpa.org/#/kaesar) considering `kaesar-pbkdf2 0.9.0` as a dependency.

As kaesar-pbkdf2 is not available via MELPA, the entire package can't be installed via the emacs packages interface (`Status: Incompatible because it depends on uninstallable packages.`).

**Comment by mhayashi1120** [comment]
available now. thanks letting me know.
